### PR TITLE
Added danish locale

### PR DESCRIPTION
**Pull request by bofrede**

### CODE REVIEW

**Comment by bofrede** [comment]
The failure on Travis is fixed by pull request #32.

**Comment by koppen** [comment]
Looks good to me, thanks @bofrede! @tigrish Any chance of getting this merged?

**Comment by bofrede** [comment]
I found out how to add a new locale in LocaleApp. @tigrish can you pull it from LocaleApp, please.
The only problem is that I am missing one field in LocaleApp:
da.helpers.page_entries_info.one_page.display_entries.zero: Ingen %{entry_name} fundet

**Comment by tigrish** [comment]
Thanks @bofrede, v0.5.0 pushed! 🎊

**Pull request merged**
