### PR TITLE
update latvian (lv) locale

### PR DESCRIPTION
**Pull request by ExClouds**

### CODE REVIEW

**Comment by pandalowry** [comment]
author not react for requests to merge. I send, but not reaction ^(

**Comment by ExClouds** [comment]
@pandalowry Just way, man.. :)

**Comment by pandalowry** [comment]
@ExClouds okay, we wait )

**Comment by tigrish** [comment]
Hey guys, sorry I haven't been merging PRs since the build is failing.
Am also totally swamped to fix CI :/

**Comment by ExClouds** [comment]
@tigrish Can You merge this and push it to new version, anyway? Ill try to help with the build error later..

**Comment by pandalowry** [comment]
@tigrish We are glad that you said! Hopefully, Travis errors will be corrected as our commits not exactly a breaking program. This is something with Travis.

**Pull request merged**
