### PR TITLE
Create ar.yml

### PR DESCRIPTION
**Pull request by PascalPixel**

### CODE REVIEW

**Comment by PascalPixel** [comment]
Paging doctor @tigrish

**Comment by tigrish** [comment]
Hey @Superpencil, it looks like there are some pluralisation forms missing :

```
expected config/locales/ar.yml to contain the following pluralization keys :
       - ar.helpers.page_entries_info.one_page.display_entries.two
       - ar.helpers.page_entries_info.one_page.display_entries.few
       - ar.helpers.page_entries_info.one_page.display_entries.many
```

This is preventing the build from passing...

**Comment by PascalPixel** [comment]
I'll go fetch those!

**Comment by PascalPixel** [comment]
#34

**Pull request closed without merging**
